// <auto-generated />
namespace Datamodel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addingpreviewfieldtoarticles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingpreviewfieldtoarticles));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251432203_Adding preview field to articles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
